services:
  # 1 Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Mapea el puerto para que puedas conectarte desde pgAdmin o DBeaver
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia: los datos no se borran si el contenedor se apaga

  # 2 Loki (Log Aggregation)
  loki:
    image: grafana/loki:latest
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  # 3 Grafana (Dashboard y Visualización)
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - loki
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  # 4 FastAPI
  api:
    build: . # Construye la imagen usando el Dockerfile de este directorio
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LOKI_URL: http://loki:3100
    depends_on:
      - db
      - loki

# Volúmenes nombrados para que los datos persistan
volumes:
  postgres_data:
  loki_data:
  grafana_data: